// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Facets;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Rules;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Run;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.SortingStrategy;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.TaskNamespace;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\composition\1\compositions\{compositionID}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCompositionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The facets property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Facets.FacetsRequestBuilder Facets
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Facets.FacetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rules property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Rules.RulesRequestBuilder Rules
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sortingStrategy property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.SortingStrategy.SortingStrategyRequestBuilder SortingStrategy
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.SortingStrategy.SortingStrategyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.WithCompositionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompositionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/composition/1/compositions/{compositionID}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.WithCompositionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCompositionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/composition/1/compositions/{compositionID}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a composition from the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_deleteComposition_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_deleteComposition_200?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_deleteComposition_200> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_deleteComposition_200>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_deleteComposition_200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a single composition in the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update and insert a composition in the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_putComposition_200"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_putComposition_200?> PutAsync(global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_putComposition_200> PutAsync(global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_putComposition_200>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_composition_putComposition_200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a composition from the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve a single composition in the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update and insert a composition in the current Algolia application.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_composition body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.WithCompositionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.WithCompositionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Composition.One.Compositions.Item.WithCompositionItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
