// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings
{
    /// <summary>
    /// Builds and executes requests for operations under \search\1\indexes\{indexName}\settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SettingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/1/indexes/{indexName}/settings{?forwardToReplicas*,getVersion*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/1/indexes/{indexName}/settings{?forwardToReplicas*,getVersion*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves an object with non-null index settings.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C___search_settingsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C___search_settingsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C___search_settingsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C___search_settingsResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C___search_settingsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update the specified index settings.Index settings that you don&apos;t specify are left unchanged.Specify `null` to reset a setting to its default value.For best performance, update the index settings before you add new records to your index.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C___search_updatedAtResponse"/></returns>
        /// <param name="body">Index settings.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C___search_updatedAtResponse?> PutAsync(global::Soenneker.Algolia.OpenApiClient.Models.C____search_indexSettings body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C___search_updatedAtResponse> PutAsync(global::Soenneker.Algolia.OpenApiClient.Models.C____search_indexSettings body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.C____search_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C___search_updatedAtResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C___search_updatedAtResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves an object with non-null index settings.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update the specified index settings.Index settings that you don&apos;t specify are left unchanged.Specify `null` to reset a setting to its default value.For best performance, update the index settings before you add new records to your index.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Index settings.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.Models.C____search_indexSettings body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.Models.C____search_indexSettings body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder.SettingsRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.Search.One.Indexes.Item.Settings.SettingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves an object with non-null index settings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SettingsRequestBuilderGetQueryParameters 
        {
            /// <summary>When set to 2, the endpoint will not include `synonyms` in the response. This parameter is here for backward compatibility.</summary>
            [QueryParameter("getVersion")]
            public int? GetVersion { get; set; }
        }
        /// <summary>
        /// Update the specified index settings.Index settings that you don&apos;t specify are left unchanged.Specify `null` to reset a setting to its default value.For best performance, update the index settings before you add new records to your index.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SettingsRequestBuilderPutQueryParameters 
        {
            /// <summary>Whether changes are applied to replica indices.</summary>
            [QueryParameter("forwardToReplicas")]
            public bool? ForwardToReplicas { get; set; }
        }
    }
}
#pragma warning restore CS0618
