// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\search\1\keys\{key}\restore
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RestoreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore.RestoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestoreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/search/1/keys/{key}/restore", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore.RestoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestoreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/search/1/keys/{key}/restore", rawUrl)
        {
        }
        /// <summary>
        /// Restores a deleted API key.Restoring resets the `validity` attribute to `0`.Algolia stores up to 1,000 API keys per application.If you create more, the oldest API keys are deleted and can&apos;t be restored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_addApiKeyResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_addApiKeyResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_addApiKeyResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_search_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_addApiKeyResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_addApiKeyResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Restores a deleted API key.Restoring resets the `validity` attribute to `0`.Algolia stores up to 1,000 API keys per application.If you create more, the oldest API keys are deleted and can&apos;t be restored.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore.RestoreRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore.RestoreRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Search.One.Keys.Item.Restore.RestoreRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
