// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies.Personalization;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\fixed\personalization\1\strategies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StrategiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The personalization property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies.Personalization.PersonalizationRequestBuilder Personalization
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies.Personalization.PersonalizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies.StrategiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StrategiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/personalization/1/strategies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Personalization.One.Strategies.StrategiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StrategiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/personalization/1/strategies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
