// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\advanced-personalization\2\users\{userID}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/advanced-personalization/2/users/{userID}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/advanced-personalization/2/users/{userID}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a user profile.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_advanced_personalization_deleteUser_200_Response_application_json_2"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_badUserID_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_unauthorized_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_invalidUserID_1">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_internalServerError_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_advanced_personalization_deleteUser_200_Response_application_json_2?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_advanced_personalization_deleteUser_200_Response_application_json_2> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_badUserID_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_unauthorized_1.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_invalidUserID_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_internalServerError_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_advanced_personalization_deleteUser_200_Response_application_json_2>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_advanced_personalization_deleteUser_200_Response_application_json_2.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a user profile.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_user_1"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_badUserID_1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_unauthorized_1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_genericNotFound_1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_invalidUserID_1">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_internalServerError_1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_user_1?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_user_1> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_badUserID_1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_unauthorized_1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_genericNotFound_1.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_invalidUserID_1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_ErrorResponses_internalServerError_1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_user_1>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_user_1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a user profile.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves a user profile.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item.WithUserItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item.WithUserItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.AdvancedPersonalization.Two.Users.Item.WithUserItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
