// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\fixed\abtesting\{path}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPathItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/abtesting/{path}{?parameters*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/abtesting/{path}{?parameters*}", rawUrl)
        {
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathDeleteResponse?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathDeleteResponse> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathDeleteResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathGetResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostResponse?> PostAsync(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostResponse> PostAsync(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutResponse?> PutAsync(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutResponse> PutAsync(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_fixed_abtesting_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathPutRequestBody body, Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Abtesting.Item.WithPathItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPathItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Query parameters to apply to the current query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters")]
            public string? Parameters { get; set; }
#nullable restore
#else
            [QueryParameter("parameters")]
            public string Parameters { get; set; }
#endif
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPathItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Query parameters to apply to the current query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters")]
            public string? Parameters { get; set; }
#nullable restore
#else
            [QueryParameter("parameters")]
            public string Parameters { get; set; }
#endif
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPathItemRequestBuilderPostQueryParameters 
        {
            /// <summary>Query parameters to apply to the current query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters")]
            public string? Parameters { get; set; }
#nullable restore
#else
            [QueryParameter("parameters")]
            public string Parameters { get; set; }
#endif
        }
        /// <summary>
        /// This method lets you send requests to the Algolia REST API.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPathItemRequestBuilderPutQueryParameters 
        {
            /// <summary>Query parameters to apply to the current query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters")]
            public string? Parameters { get; set; }
#nullable restore
#else
            [QueryParameter("parameters")]
            public string Parameters { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
