// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Languages;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Settings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\merged-openapi\search\1\dictionaries\*
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The languages property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/search/1/dictionaries/*", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Dictionaries.Asterisk.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/search/1/dictionaries/*", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
