// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats.Urls;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\crawler\1\crawlers\{id}\stats
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The urls property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats.Urls.UrlsRequestBuilder Urls
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats.Urls.UrlsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/crawler/1/crawlers/{id}/stats", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Crawler.One.Crawlers.Item.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/crawler/1/crawlers/{id}/stats", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
