// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\crawler\1\crawlers\{id}\tasks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Algolia.OpenApiClient.fixed.mergedOpenapi.fixed.crawler.One.crawlers.item.tasks.item collection</summary>
        /// <param name="position">Task ID.</param>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.Item.WithTaskItemRequestBuilder"/></returns>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.Item.WithTaskItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("taskID", position);
                return new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.Item.WithTaskItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/crawler/1/crawlers/{id}/tasks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Crawler.One.Crawlers.Item.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/crawler/1/crawlers/{id}/tasks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
