// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.Item;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.NoResults;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\analytics\2\filters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FiltersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The noResults property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.NoResults.NoResultsRequestBuilder NoResults
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.NoResults.NoResultsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Algolia.OpenApiClient.mergedOpenapi.analytics.Two.filters.item collection</summary>
        /// <param name="position">Attribute name.</param>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.Item.WithAttributeItemRequestBuilder"/></returns>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.Item.WithAttributeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("attribute", position);
                return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.Item.WithAttributeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FiltersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/analytics/2/filters?index={index}{&endDate*,limit*,offset*,search*,startDate*,tags*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FiltersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/analytics/2/filters?index={index}{&endDate*,limit*,offset*,search*,startDate*,tags*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves the 1,000 most frequently used filter attributes.These are attributes of your records that you included in the `attributesForFaceting` setting.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_getTopFilterAttributesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_getTopFilterAttributesResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder.FiltersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_getTopFilterAttributesResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder.FiltersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_analytics_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_getTopFilterAttributesResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_getTopFilterAttributesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the 1,000 most frequently used filter attributes.These are attributes of your records that you included in the `attributesForFaceting` setting.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder.FiltersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder.FiltersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Analytics.Two.Filters.FiltersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves the 1,000 most frequently used filter attributes.These are attributes of your records that you included in the `attributesForFaceting` setting.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FiltersRequestBuilderGetQueryParameters 
        {
            /// <summary>End date of the period to analyze, in `YYYY-MM-DD` format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endDate")]
            public string? EndDate { get; set; }
#nullable restore
#else
            [QueryParameter("endDate")]
            public string EndDate { get; set; }
#endif
            /// <summary>Index name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("index")]
            public string? Index { get; set; }
#nullable restore
#else
            [QueryParameter("index")]
            public string Index { get; set; }
#endif
            /// <summary>Number of items to return.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Position of the first item to return.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Search query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Start date of the period to analyze, in `YYYY-MM-DD` format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startDate")]
            public string? StartDate { get; set; }
#nullable restore
#else
            [QueryParameter("startDate")]
            public string StartDate { get; set; }
#endif
            /// <summary>Tags by which to segment the analytics.You can combine multiple tags with `OR` and `AND`.Tags must be URL-encoded.For more information, see [Segment your analytics data](https://www.algolia.com/doc/guides/search-analytics/guides/segments).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string Tags { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
