// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.AccountCopyIndex;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.BrowseObjects;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ChunkedBatch;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.DeleteObjects;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.GenerateSecuredApiKey;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.IndexExists;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.Item;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjects;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjectsWithTransformation;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjects;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjectsWithTransformation;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjects;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjectsWithTransformation;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SetClientApiKey;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForApiKey;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForAppTask;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForTask;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\merged-openapi\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accountCopyIndex property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.AccountCopyIndex.AccountCopyIndexRequestBuilder AccountCopyIndex
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.AccountCopyIndex.AccountCopyIndexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The browseObjects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.BrowseObjects.BrowseObjectsRequestBuilder BrowseObjects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.BrowseObjects.BrowseObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chunkedBatch property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ChunkedBatch.ChunkedBatchRequestBuilder ChunkedBatch
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ChunkedBatch.ChunkedBatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteObjects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.DeleteObjects.DeleteObjectsRequestBuilder DeleteObjects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.DeleteObjects.DeleteObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The generateSecuredApiKey property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder GenerateSecuredApiKey
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexExists property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.IndexExists.IndexExistsRequestBuilder IndexExists
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.IndexExists.IndexExistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The One property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.OneRequestBuilder One
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.One.OneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partialUpdateObjects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjects.PartialUpdateObjectsRequestBuilder PartialUpdateObjects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjects.PartialUpdateObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partialUpdateObjectsWithTransformation property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjectsWithTransformation.PartialUpdateObjectsWithTransformationRequestBuilder PartialUpdateObjectsWithTransformation
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.PartialUpdateObjectsWithTransformation.PartialUpdateObjectsWithTransformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replaceAllObjects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjects.ReplaceAllObjectsRequestBuilder ReplaceAllObjects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjects.ReplaceAllObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replaceAllObjectsWithTransformation property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjectsWithTransformation.ReplaceAllObjectsWithTransformationRequestBuilder ReplaceAllObjectsWithTransformation
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.ReplaceAllObjectsWithTransformation.ReplaceAllObjectsWithTransformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saveObjects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjects.SaveObjectsRequestBuilder SaveObjects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjects.SaveObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saveObjectsWithTransformation property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjectsWithTransformation.SaveObjectsWithTransformationRequestBuilder SaveObjectsWithTransformation
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SaveObjectsWithTransformation.SaveObjectsWithTransformationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setClientApiKey property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SetClientApiKey.SetClientApiKeyRequestBuilder SetClientApiKey
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SetClientApiKey.SetClientApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waitForApiKey property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForApiKey.WaitForApiKeyRequestBuilder WaitForApiKey
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForApiKey.WaitForApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waitForAppTask property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForAppTask.WaitForAppTaskRequestBuilder WaitForAppTask
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForAppTask.WaitForAppTaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waitForTask property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForTask.WaitForTaskRequestBuilder WaitForTask
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.WaitForTask.WaitForTaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Algolia.OpenApiClient.fixed.mergedOpenapi.fixed.mergedOpenapi.search.item collection</summary>
        /// <param name="position">Path of the endpoint, for example `1/newFeature`.</param>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.Item.WithPathItemRequestBuilder"/></returns>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/search", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
