// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\fixed\monitoring\1\incidents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncidentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Algolia.OpenApiClient.mergedOpenapi.fixed.monitoring.One.incidents.item collection</summary>
        /// <param name="position">Subset of clusters, separated by commas.</param>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.Item.WithClustersItemRequestBuilder"/></returns>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.Item.WithClustersItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("clusters", position);
                return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.Item.WithClustersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncidentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/monitoring/1/incidents", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncidentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/monitoring/1/incidents", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves known incidents for all clusters.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsGetResponse>(requestInfo, global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves known incidents for all clusters.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.Monitoring.One.Incidents.IncidentsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
