// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Dictionaries;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Indexes;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Keys;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Logs;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Security;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.TaskNamespace;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\merged-openapi\fixed\search\1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dictionaries property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Dictionaries.DictionariesRequestBuilder Dictionaries
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Dictionaries.DictionariesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexes property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Indexes.IndexesRequestBuilder Indexes
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Indexes.IndexesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Logs.LogsRequestBuilder Logs
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The security property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Security.SecurityRequestBuilder Security
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.Security.SecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.OneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/fixed/search/1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.MergedOpenapi.Fixed.Search.One.OneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/merged-openapi/fixed/search/1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
