// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartialMember1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthInputPartial : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial? AuthAlgoliaInsightsPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial AuthAlgoliaInsightsPartial { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial? AuthAlgoliaPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial AuthAlgoliaPartial { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial? AuthApiKeyPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial AuthApiKeyPartial { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial? AuthBasicPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial AuthBasicPartial { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial? AuthGoogleServiceAccountPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial AuthGoogleServiceAccountPartial { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartialMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartialMember1? AuthInputPartialMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartialMember1 AuthInputPartialMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial? AuthOAuthPartial { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial AuthOAuthPartial { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartial"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartial CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartial();
            if("AuthAlgoliaInsightsPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthAlgoliaInsightsPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial();
            }
            else if("AuthAlgoliaPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthAlgoliaPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial();
            }
            else if("AuthApiKeyPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthApiKeyPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial();
            }
            else if("AuthBasicPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthBasicPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial();
            }
            else if("AuthGoogleServiceAccountPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthGoogleServiceAccountPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial();
            }
            else if("AuthOAuthPartial".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AuthOAuthPartial = new global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AuthAlgoliaInsightsPartial != null)
            {
                return AuthAlgoliaInsightsPartial.GetFieldDeserializers();
            }
            else if(AuthAlgoliaPartial != null)
            {
                return AuthAlgoliaPartial.GetFieldDeserializers();
            }
            else if(AuthApiKeyPartial != null)
            {
                return AuthApiKeyPartial.GetFieldDeserializers();
            }
            else if(AuthBasicPartial != null)
            {
                return AuthBasicPartial.GetFieldDeserializers();
            }
            else if(AuthGoogleServiceAccountPartial != null)
            {
                return AuthGoogleServiceAccountPartial.GetFieldDeserializers();
            }
            else if(AuthInputPartialMember1 != null)
            {
                return AuthInputPartialMember1.GetFieldDeserializers();
            }
            else if(AuthOAuthPartial != null)
            {
                return AuthOAuthPartial.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AuthAlgoliaInsightsPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaInsightsPartial>(null, AuthAlgoliaInsightsPartial);
            }
            else if(AuthAlgoliaPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthAlgoliaPartial>(null, AuthAlgoliaPartial);
            }
            else if(AuthApiKeyPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthApiKeyPartial>(null, AuthApiKeyPartial);
            }
            else if(AuthBasicPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthBasicPartial>(null, AuthBasicPartial);
            }
            else if(AuthGoogleServiceAccountPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthGoogleServiceAccountPartial>(null, AuthGoogleServiceAccountPartial);
            }
            else if(AuthInputPartialMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthInputPartialMember1>(null, AuthInputPartialMember1);
            }
            else if(AuthOAuthPartial != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.AuthOAuthPartial>(null, AuthOAuthPartial);
            }
        }
    }
}
#pragma warning restore CS0618
