// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Effect of the rule.For more information, see [Consequences](https://www.algolia.com/doc/guides/managing-results/rules/rules-overview/#consequences).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C__search_consequence : IParsable
    {
        /// <summary>&quot;Determines whether promoted records must also match active filters for the consequence to apply.This ensures user-applied filters take priority and irrelevant matches aren&apos;t shown.For example, if you promote a record with `color: red` but the user filters for `color: blue`,the \&quot;red\&quot; record won&apos;t be shown.&gt; In the Algolia dashboard, when you use the **Pin an item** consequence, `filterPromotes` appears as the checkbox: **Pinned items must match active filters to be displayed.** For examples, see [Promote results with rules](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/promote-hits/#promote-results-matching-active-filters).&quot;</summary>
        public bool? FilterPromotes { get; set; }
        /// <summary>Records you want to hide from the search results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_hide>? Hide { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_hide> Hide { get; set; }
#endif
        /// <summary>The params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequenceParams? Params { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequenceParams Params { get; set; }
#endif
        /// <summary>Records you want to pin to a specific position in the search results.You can promote up to 300 records, either individually, or as groups of up to 100 records each.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C__search_promote>? Promote { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C__search_promote> Promote { get; set; }
#endif
        /// <summary>&quot;Redirect to a virtual replica index.This consequence is only valid for rules with `scope: redirect`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_redirect? Redirect { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_redirect Redirect { get; set; }
#endif
        /// <summary>A JSON object with custom data that will be appended to the `userData` array in the response.This object isn&apos;t interpreted by the API and is limited to 1&amp;nbsp;kB of minified JSON.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_userData? UserData { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_userData UserData { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filterPromotes", n => { FilterPromotes = n.GetBoolValue(); } },
                { "hide", n => { Hide = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_hide>(global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_hide.CreateFromDiscriminatorValue)?.AsList(); } },
                { "params", n => { Params = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequenceParams>(global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequenceParams.CreateFromDiscriminatorValue); } },
                { "promote", n => { Promote = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C__search_promote>(global::Soenneker.Algolia.OpenApiClient.Models.C__search_promote.CreateFromDiscriminatorValue)?.AsList(); } },
                { "redirect", n => { Redirect = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_redirect>(global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_redirect.CreateFromDiscriminatorValue); } },
                { "userData", n => { UserData = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_userData>(global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_userData.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("filterPromotes", FilterPromotes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_hide>("hide", Hide);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequenceParams>("params", Params);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C__search_promote>("promote", Promote);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_redirect>("redirect", Redirect);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C__search_consequence_userData>("userData", UserData);
        }
    }
}
#pragma warning restore CS0618
