// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class C_ingestion_Transformation_1 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The authentications associated with the current transformation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AuthenticationIDs { get; set; }
#nullable restore
#else
        public List<string> AuthenticationIDs { get; set; }
#endif
        /// <summary>It is deprecated. Use the `input` field with proper `type` instead to specify the transformation code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Date and time when the resource was created, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>A descriptive name for your transformation of what it does.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The input for the transformation, which can be either code or a no-code configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationInput_1? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationInput_1 Input { get; set; }
#endif
        /// <summary>The uniquely identified name of your transformation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_owner_1? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_owner_1 Owner { get; set; }
#endif
        /// <summary>Universally unique identifier (UUID) of a transformation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransformationID { get; set; }
#nullable restore
#else
        public string TransformationID { get; set; }
#endif
        /// <summary>The type of transformation, which can be either &apos;code&apos; or &apos;noCode&apos;.</summary>
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationType_1? Type { get; set; }
        /// <summary>Date and time when the resource was last updated, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Transformation_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Transformation_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Transformation_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authenticationIDs", n => { AuthenticationIDs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationInput_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationInput_1.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_owner_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_owner_1.CreateFromDiscriminatorValue); } },
                { "transformationID", n => { TransformationID = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationType_1>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("authenticationIDs", AuthenticationIDs);
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationInput_1>("input", Input);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_owner_1>("owner", Owner);
            writer.WriteStringValue("transformationID", TransformationID);
            writer.WriteEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TransformationType_1>("type", Type);
            writer.WriteStringValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
