// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// API request body for updating a task.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_ingestion_TaskReplace_1 : IParsable
    {
        /// <summary>Action to perform on the Algolia index.</summary>
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1? Action { get; set; }
        /// <summary>Cron expression for the task&apos;s schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cron { get; set; }
#nullable restore
#else
        public string Cron { get; set; }
#endif
        /// <summary>Date and time when the last cursor was created, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Universally unique identifier (UUID) of a destination resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationID { get; set; }
#nullable restore
#else
        public string DestinationID { get; set; }
#endif
        /// <summary>Whether the task is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Maximum accepted percentage of failures for a task run to finish successfully.</summary>
        public int? FailureThreshold { get; set; }
        /// <summary>Configuration of the task, depending on its type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskInput_1? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskInput_1 Input { get; set; }
#endif
        /// <summary>Notifications settings for a task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Notifications_1? Notifications { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Notifications_1 Notifications { get; set; }
#endif
        /// <summary>Set of rules for a task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Policies_1? Policies { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Policies_1 Policies { get; set; }
#endif
        /// <summary>Action to perform on the Algolia index.</summary>
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1? SubscriptionAction { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskReplace_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskReplace_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskReplace_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1>(); } },
                { "cron", n => { Cron = n.GetStringValue(); } },
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "destinationID", n => { DestinationID = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "failureThreshold", n => { FailureThreshold = n.GetIntValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskInput_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskInput_1.CreateFromDiscriminatorValue); } },
                { "notifications", n => { Notifications = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Notifications_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Notifications_1.CreateFromDiscriminatorValue); } },
                { "policies", n => { Policies = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Policies_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Policies_1.CreateFromDiscriminatorValue); } },
                { "subscriptionAction", n => { SubscriptionAction = n.GetEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1>("action", Action);
            writer.WriteStringValue("cron", Cron);
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteStringValue("destinationID", DestinationID);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("failureThreshold", FailureThreshold);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_TaskInput_1>("input", Input);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Notifications_1>("notifications", Notifications);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Policies_1>("policies", Policies);
            writer.WriteEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_ActionType_1>("subscriptionAction", SubscriptionAction);
        }
    }
}
#pragma warning restore CS0618
