// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_merged_openapi_fixed_getTopHitsResponse_1 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1? CMergedOpenapiMergedOpenapiFixedTopHitsResponse1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1 CMergedOpenapiMergedOpenapiFixedTopHitsResponse1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1? CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1 CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1? CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1 CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse_1();
            if("C_merged_openapi_merged_openapi_fixed_topHitsResponse_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponse1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1();
            }
            else if("C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1();
            }
            else if("C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiMergedOpenapiFixedTopHitsResponse1 != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponse1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1 != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1 != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiMergedOpenapiFixedTopHitsResponse1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse_1>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponse1);
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics_1>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics1);
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics_1>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics1);
            }
        }
    }
}
#pragma warning restore CS0618
