// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_compositionBehavior_2 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2? CMergedOpenapiCompositionInjectionBehavior2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2 CMergedOpenapiCompositionInjectionBehavior2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2? CMergedOpenapiCompositionMultifeedBehavior2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2 CMergedOpenapiCompositionMultifeedBehavior2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionBehavior_2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionBehavior_2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionBehavior_2();
            if("C_merged_openapi_compositionInjectionBehavior_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiCompositionInjectionBehavior2 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2();
            }
            else if("C_merged_openapi_compositionMultifeedBehavior_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiCompositionMultifeedBehavior2 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiCompositionInjectionBehavior2 != null)
            {
                return CMergedOpenapiCompositionInjectionBehavior2.GetFieldDeserializers();
            }
            else if(CMergedOpenapiCompositionMultifeedBehavior2 != null)
            {
                return CMergedOpenapiCompositionMultifeedBehavior2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiCompositionInjectionBehavior2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionInjectionBehavior_2>(null, CMergedOpenapiCompositionInjectionBehavior2);
            }
            else if(CMergedOpenapiCompositionMultifeedBehavior2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_compositionMultifeedBehavior_2>(null, CMergedOpenapiCompositionMultifeedBehavior2);
            }
        }
    }
}
#pragma warning restore CS0618
