// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_SourceInput_1 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1? CMergedOpenapiSourceBigCommerce1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1 CMergedOpenapiSourceBigCommerce1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1? CMergedOpenapiSourceBigQuery1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1 CMergedOpenapiSourceBigQuery1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1? CMergedOpenapiSourceCommercetools1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1 CMergedOpenapiSourceCommercetools1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1? CMergedOpenapiSourceCSV1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1 CMergedOpenapiSourceCSV1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1? CMergedOpenapiSourceDocker1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1 CMergedOpenapiSourceDocker1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1? CMergedOpenapiSourceGA4BigQueryExport1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1 CMergedOpenapiSourceGA4BigQueryExport1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1? CMergedOpenapiSourceJSON1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1 CMergedOpenapiSourceJSON1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1? CMergedOpenapiSourceShopify1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1 CMergedOpenapiSourceShopify1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceInput_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceInput_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceInput_1();
            if("C_merged_openapi_SourceBigCommerce_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceBigCommerce1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1();
            }
            else if("C_merged_openapi_SourceBigQuery_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceBigQuery1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1();
            }
            else if("C_merged_openapi_SourceCSV_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceCSV1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1();
            }
            else if("C_merged_openapi_SourceCommercetools_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceCommercetools1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1();
            }
            else if("C_merged_openapi_SourceDocker_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceDocker1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1();
            }
            else if("C_merged_openapi_SourceGA4BigQueryExport_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceGA4BigQueryExport1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1();
            }
            else if("C_merged_openapi_SourceJSON_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceJSON1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1();
            }
            else if("C_merged_openapi_SourceShopify_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiSourceShopify1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiSourceBigCommerce1 != null)
            {
                return CMergedOpenapiSourceBigCommerce1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceBigQuery1 != null)
            {
                return CMergedOpenapiSourceBigQuery1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceCommercetools1 != null)
            {
                return CMergedOpenapiSourceCommercetools1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceCSV1 != null)
            {
                return CMergedOpenapiSourceCSV1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceDocker1 != null)
            {
                return CMergedOpenapiSourceDocker1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceGA4BigQueryExport1 != null)
            {
                return CMergedOpenapiSourceGA4BigQueryExport1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceJSON1 != null)
            {
                return CMergedOpenapiSourceJSON1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiSourceShopify1 != null)
            {
                return CMergedOpenapiSourceShopify1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiSourceBigCommerce1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigCommerce_1>(null, CMergedOpenapiSourceBigCommerce1);
            }
            else if(CMergedOpenapiSourceBigQuery1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceBigQuery_1>(null, CMergedOpenapiSourceBigQuery1);
            }
            else if(CMergedOpenapiSourceCommercetools1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCommercetools_1>(null, CMergedOpenapiSourceCommercetools1);
            }
            else if(CMergedOpenapiSourceCSV1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceCSV_1>(null, CMergedOpenapiSourceCSV1);
            }
            else if(CMergedOpenapiSourceDocker1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceDocker_1>(null, CMergedOpenapiSourceDocker1);
            }
            else if(CMergedOpenapiSourceGA4BigQueryExport1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceGA4BigQueryExport_1>(null, CMergedOpenapiSourceGA4BigQueryExport1);
            }
            else if(CMergedOpenapiSourceJSON1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceJSON_1>(null, CMergedOpenapiSourceJSON1);
            }
            else if(CMergedOpenapiSourceShopify1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_SourceShopify_1>(null, CMergedOpenapiSourceShopify1);
            }
        }
    }
}
#pragma warning restore CS0618
