// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi__ingestion_SourceInput_1 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1? CMergedOpenapiIngestionSourceBigCommerce1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1 CMergedOpenapiIngestionSourceBigCommerce1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1? CMergedOpenapiIngestionSourceBigQuery1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1 CMergedOpenapiIngestionSourceBigQuery1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1? CMergedOpenapiIngestionSourceCommercetools1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1 CMergedOpenapiIngestionSourceCommercetools1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1? CMergedOpenapiIngestionSourceCSV1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1 CMergedOpenapiIngestionSourceCSV1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1? CMergedOpenapiIngestionSourceDocker1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1 CMergedOpenapiIngestionSourceDocker1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1? CMergedOpenapiIngestionSourceGA4BigQueryExport1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1 CMergedOpenapiIngestionSourceGA4BigQueryExport1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1? CMergedOpenapiIngestionSourceJSON1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1 CMergedOpenapiIngestionSourceJSON1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1? CMergedOpenapiIngestionSourceShopify1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1 CMergedOpenapiIngestionSourceShopify1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceInput_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceInput_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceInput_1();
            if("C_merged_openapi__ingestion_SourceBigCommerce_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceBigCommerce1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1();
            }
            else if("C_merged_openapi__ingestion_SourceBigQuery_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceBigQuery1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1();
            }
            else if("C_merged_openapi__ingestion_SourceCSV_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceCSV1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1();
            }
            else if("C_merged_openapi__ingestion_SourceCommercetools_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceCommercetools1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1();
            }
            else if("C_merged_openapi__ingestion_SourceDocker_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceDocker1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1();
            }
            else if("C_merged_openapi__ingestion_SourceGA4BigQueryExport_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceGA4BigQueryExport1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1();
            }
            else if("C_merged_openapi__ingestion_SourceJSON_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceJSON1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1();
            }
            else if("C_merged_openapi__ingestion_SourceShopify_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiIngestionSourceShopify1 = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiIngestionSourceBigCommerce1 != null)
            {
                return CMergedOpenapiIngestionSourceBigCommerce1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceBigQuery1 != null)
            {
                return CMergedOpenapiIngestionSourceBigQuery1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceCommercetools1 != null)
            {
                return CMergedOpenapiIngestionSourceCommercetools1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceCSV1 != null)
            {
                return CMergedOpenapiIngestionSourceCSV1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceDocker1 != null)
            {
                return CMergedOpenapiIngestionSourceDocker1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceGA4BigQueryExport1 != null)
            {
                return CMergedOpenapiIngestionSourceGA4BigQueryExport1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceJSON1 != null)
            {
                return CMergedOpenapiIngestionSourceJSON1.GetFieldDeserializers();
            }
            else if(CMergedOpenapiIngestionSourceShopify1 != null)
            {
                return CMergedOpenapiIngestionSourceShopify1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiIngestionSourceBigCommerce1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigCommerce_1>(null, CMergedOpenapiIngestionSourceBigCommerce1);
            }
            else if(CMergedOpenapiIngestionSourceBigQuery1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceBigQuery_1>(null, CMergedOpenapiIngestionSourceBigQuery1);
            }
            else if(CMergedOpenapiIngestionSourceCommercetools1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCommercetools_1>(null, CMergedOpenapiIngestionSourceCommercetools1);
            }
            else if(CMergedOpenapiIngestionSourceCSV1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceCSV_1>(null, CMergedOpenapiIngestionSourceCSV1);
            }
            else if(CMergedOpenapiIngestionSourceDocker1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceDocker_1>(null, CMergedOpenapiIngestionSourceDocker1);
            }
            else if(CMergedOpenapiIngestionSourceGA4BigQueryExport1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceGA4BigQueryExport_1>(null, CMergedOpenapiIngestionSourceGA4BigQueryExport1);
            }
            else if(CMergedOpenapiIngestionSourceJSON1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceJSON_1>(null, CMergedOpenapiIngestionSourceJSON1);
            }
            else if(CMergedOpenapiIngestionSourceShopify1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi__ingestion_SourceShopify_1>(null, CMergedOpenapiIngestionSourceShopify1);
            }
        }
    }
}
#pragma warning restore CS0618
