// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_C_merged_openapi_TaskInput : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput? CMergedOpenapiCMergedOpenapiDockerStreamsInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput CMergedOpenapiCMergedOpenapiDockerStreamsInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput? CMergedOpenapiCMergedOpenapiShopifyInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput CMergedOpenapiCMergedOpenapiShopifyInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput? CMergedOpenapiCMergedOpenapiStreamingInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput CMergedOpenapiCMergedOpenapiStreamingInput { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_TaskInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_TaskInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_TaskInput();
            if("C_merged_openapi_C_merged_openapi_DockerStreamsInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiCMergedOpenapiDockerStreamsInput = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput();
            }
            else if("C_merged_openapi_C_merged_openapi_ShopifyInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiCMergedOpenapiShopifyInput = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput();
            }
            else if("C_merged_openapi_C_merged_openapi_StreamingInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiCMergedOpenapiStreamingInput = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiCMergedOpenapiDockerStreamsInput != null)
            {
                return CMergedOpenapiCMergedOpenapiDockerStreamsInput.GetFieldDeserializers();
            }
            else if(CMergedOpenapiCMergedOpenapiShopifyInput != null)
            {
                return CMergedOpenapiCMergedOpenapiShopifyInput.GetFieldDeserializers();
            }
            else if(CMergedOpenapiCMergedOpenapiStreamingInput != null)
            {
                return CMergedOpenapiCMergedOpenapiStreamingInput.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiCMergedOpenapiDockerStreamsInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_DockerStreamsInput>(null, CMergedOpenapiCMergedOpenapiDockerStreamsInput);
            }
            else if(CMergedOpenapiCMergedOpenapiShopifyInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_ShopifyInput>(null, CMergedOpenapiCMergedOpenapiShopifyInput);
            }
            else if(CMergedOpenapiCMergedOpenapiStreamingInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_C_merged_openapi_StreamingInput>(null, CMergedOpenapiCMergedOpenapiStreamingInput);
            }
        }
    }
}
#pragma warning restore CS0618
