// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class C_merged_openapi_fixed_variant : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Search parameters applied to this variant when the same index is used for multiple variants.Only present if custom search parameters were provided during test creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant_customSearchParameters? CustomSearchParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant_customSearchParameters CustomSearchParameters { get; set; }
#endif
        /// <summary>Description for this variant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Estimated number of searches required to achieve the desired statistical significance.The A/B test configuration must include a `minimumDetectableEffect` setting for this number to be included in the response.</summary>
        public int? EstimatedSampleSize { get; set; }
        /// <summary>Index name of the A/B test variant (case-sensitive).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Index { get; set; }
#nullable restore
#else
        public string Index { get; set; }
#endif
        /// <summary>Variant specific metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variantMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variantMetadata Metadata { get; set; }
#endif
        /// <summary>All ABTest metrics that were defined during test creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_metricResult>? Metrics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_metricResult> Metrics { get; set; }
#endif
        /// <summary>Percentage of search requests each variant receives.</summary>
        public int? TrafficPercentage { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customSearchParameters", n => { CustomSearchParameters = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant_customSearchParameters>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant_customSearchParameters.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "estimatedSampleSize", n => { EstimatedSampleSize = n.GetIntValue(); } },
                { "index", n => { Index = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variantMetadata>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variantMetadata.CreateFromDiscriminatorValue); } },
                { "metrics", n => { Metrics = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_metricResult>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_metricResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "trafficPercentage", n => { TrafficPercentage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variant_customSearchParameters>("customSearchParameters", CustomSearchParameters);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("estimatedSampleSize", EstimatedSampleSize);
            writer.WriteStringValue("index", Index);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_variantMetadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_fixed_metricResult>("metrics", Metrics);
            writer.WriteIntValue("trafficPercentage", TrafficPercentage);
        }
    }
}
#pragma warning restore CS0618
