// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Operation to perform on the index.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum C_merged_openapi_C_merged_openapi_operationType
    {
        [EnumMember(Value = "move")]
        #pragma warning disable CS1591
        Move,
        #pragma warning restore CS1591
        [EnumMember(Value = "copy")]
        #pragma warning disable CS1591
        Copy,
        #pragma warning restore CS1591
    }
}
