// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_merged_openapi_fixed_getTopHitsResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse? CMergedOpenapiMergedOpenapiFixedTopHitsResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse CMergedOpenapiMergedOpenapiFixedTopHitsResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics? CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics? CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_getTopHitsResponse();
            if("C_merged_openapi_merged_openapi_fixed_topHitsResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponse = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse();
            }
            else if("C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics();
            }
            else if("C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics = new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiMergedOpenapiFixedTopHitsResponse != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponse.GetFieldDeserializers();
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics.GetFieldDeserializers();
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics != null)
            {
                return CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CMergedOpenapiMergedOpenapiFixedTopHitsResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponse>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponse);
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithAnalytics>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithAnalytics);
            }
            else if(CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_fixed_topHitsResponseWithRevenueAnalytics>(null, CMergedOpenapiMergedOpenapiFixedTopHitsResponseWithRevenueAnalytics);
            }
        }
    }
}
#pragma warning restore CS0618
