// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class C_merged_openapi_personalizationStrategyParams : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Scores associated with each event.The higher the scores, the higher the impact of those events on the personalization of search results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_eventsScoring>? EventsScoring { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_eventsScoring> EventsScoring { get; set; }
#endif
        /// <summary>Scores associated with each facet.The higher the scores, the higher the impact of those events on the personalization of search results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_facetsScoring>? FacetsScoring { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_facetsScoring> FacetsScoring { get; set; }
#endif
        /// <summary>Impact of personalization on the search results.If set to 0, personalization has no impact on the search results.</summary>
        public int? PersonalizationImpact { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_personalizationStrategyParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_personalizationStrategyParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_personalizationStrategyParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eventsScoring", n => { EventsScoring = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_eventsScoring>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_eventsScoring.CreateFromDiscriminatorValue)?.AsList(); } },
                { "facetsScoring", n => { FacetsScoring = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_facetsScoring>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_facetsScoring.CreateFromDiscriminatorValue)?.AsList(); } },
                { "personalizationImpact", n => { PersonalizationImpact = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_eventsScoring>("eventsScoring", EventsScoring);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_facetsScoring>("facetsScoring", FacetsScoring);
            writer.WriteIntValue("personalizationImpact", PersonalizationImpact);
        }
    }
}
#pragma warning restore CS0618
