// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Lets you add options to HTTP requests made by the crawler.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_merged_openapi_requestOptions_2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Headers to add to all requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_headers_2? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_headers_2 Headers { get; set; }
#endif
        /// <summary>Proxy for all crawler requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Proxy { get; set; }
#nullable restore
#else
        public string Proxy { get; set; }
#endif
        /// <summary>Maximum number of retries to crawl one URL.</summary>
        public int? Retries { get; set; }
        /// <summary>Timeout in milliseconds for the crawl.</summary>
        public int? Timeout { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_requestOptions_2"/> and sets the default values.
        /// </summary>
        public C_merged_openapi_merged_openapi_requestOptions_2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_requestOptions_2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_requestOptions_2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_requestOptions_2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_headers_2>(global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_headers_2.CreateFromDiscriminatorValue); } },
                { "proxy", n => { Proxy = n.GetStringValue(); } },
                { "retries", n => { Retries = n.GetIntValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_merged_openapi_headers_2>("headers", Headers);
            writer.WriteStringValue("proxy", Proxy);
            writer.WriteIntValue("retries", Retries);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
