// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>The strategy to use to fetch the data.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum C_merged_openapi_DockerStreamsSyncMode_3
    {
        [EnumMember(Value = "incremental")]
        #pragma warning disable CS1591
        Incremental,
        #pragma warning restore CS1591
        [EnumMember(Value = "fullTable")]
        #pragma warning disable CS1591
        FullTable,
        #pragma warning restore CS1591
    }
}
