// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>&quot;Which indexing operation to perform:- `addObject`: adds records to an index.   Equivalent to the \&quot;Add a new record (with auto-generated object ID)\&quot; operation.- `updateObject`: adds or replaces records in an index.   Equivalent to the \&quot;Add or replace a record\&quot; operation.- `partialUpdateObject`: adds or updates attributes within records.   Equivalent to the \&quot;Add or update attributes\&quot; operation with the `createIfNoExists` parameter set to true.   (If a record with the specified `objectID` doesn&apos;t exist in the specified index, this action creates adds the record to the index)- `partialUpdateObjectNoCreate`: same as `partialUpdateObject`, but with `createIfNoExists` set to false.   (A record isn&apos;t added to the index if its `objectID` doesn&apos;t exist)- `deleteObject`: delete records from an index.  Equivalent to the \&quot;Delete a record\&quot; operation.- `delete`. Delete an index. Equivalent to the \&quot;Delete an index\&quot; operation.- `clear`: delete all records from an index. Equivalent to the \&quot;Delete all records from an index operation\&quot;.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum C_merged_openapi_C_merged_openapi_search_action
    {
        [EnumMember(Value = "addObject")]
        #pragma warning disable CS1591
        AddObject,
        #pragma warning restore CS1591
        [EnumMember(Value = "updateObject")]
        #pragma warning disable CS1591
        UpdateObject,
        #pragma warning restore CS1591
        [EnumMember(Value = "partialUpdateObject")]
        #pragma warning disable CS1591
        PartialUpdateObject,
        #pragma warning restore CS1591
        [EnumMember(Value = "partialUpdateObjectNoCreate")]
        #pragma warning disable CS1591
        PartialUpdateObjectNoCreate,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleteObject")]
        #pragma warning disable CS1591
        DeleteObject,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "clear")]
        #pragma warning disable CS1591
        Clear,
        #pragma warning restore CS1591
    }
}
