// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Details about the response, such as error messages.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum C_merged_openapi_badUserID_3
    {
        [EnumMember(Value = "Invalid userID format")]
        #pragma warning disable CS1591
        InvalidUserIDFormat,
        #pragma warning restore CS1591
    }
}
