// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Fixed_insideBoundingBox : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1? FixedInsideBoundingBoxMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1 FixedInsideBoundingBoxMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5? InsideBoundingBoxArrayWrapper5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5 InsideBoundingBoxArrayWrapper5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4? InsideBoundingBoxBranch1Wrapper4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4 InsideBoundingBoxBranch1Wrapper4 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBox();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FixedInsideBoundingBoxMember1 = new global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1();
            }
            else if("insideBoundingBoxArray".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsideBoundingBoxArrayWrapper5 = new global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5();
            }
            else if("insideBoundingBox_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsideBoundingBoxBranch1Wrapper4 = new global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FixedInsideBoundingBoxMember1 != null)
            {
                return FixedInsideBoundingBoxMember1.GetFieldDeserializers();
            }
            else if(InsideBoundingBoxArrayWrapper5 != null)
            {
                return InsideBoundingBoxArrayWrapper5.GetFieldDeserializers();
            }
            else if(InsideBoundingBoxBranch1Wrapper4 != null)
            {
                return InsideBoundingBoxBranch1Wrapper4.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(FixedInsideBoundingBoxMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Fixed_insideBoundingBoxMember1>(null, FixedInsideBoundingBoxMember1);
            }
            else if(InsideBoundingBoxArrayWrapper5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBoxArray_Wrapper_5>(null, InsideBoundingBoxArrayWrapper5);
            }
            else if(InsideBoundingBoxBranch1Wrapper4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.InsideBoundingBox_Branch1_Wrapper_4>(null, InsideBoundingBoxBranch1Wrapper4);
            }
        }
    }
}
#pragma warning restore CS0618
