// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Task run type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ingestion_RunType
    {
        [EnumMember(Value = "reindex")]
        #pragma warning disable CS1591
        Reindex,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "discover")]
        #pragma warning disable CS1591
        Discover,
        #pragma warning restore CS1591
        [EnumMember(Value = "validate")]
        #pragma warning disable CS1591
        Validate,
        #pragma warning restore CS1591
        [EnumMember(Value = "push")]
        #pragma warning disable CS1591
        Push,
        #pragma warning restore CS1591
    }
}
