// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ingestion_listDestinations_200_Response_application_json_3 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The destinations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Destination_1>? Destinations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Destination_1> Destinations { get; set; }
#endif
        /// <summary>Paginated API response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Pagination_2? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Pagination_2 Pagination { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Ingestion_listDestinations_200_Response_application_json_3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Ingestion_listDestinations_200_Response_application_json_3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.Ingestion_listDestinations_200_Response_application_json_3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "destinations", n => { Destinations = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Destination_1>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Destination_1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Pagination_2>(global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Pagination_2.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Destination_1>("destinations", Destinations);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.C_ingestion_Pagination_2>("pagination", Pagination);
        }
    }
}
#pragma warning restore CS0618
