// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Dictionary language.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Languages : IParsable
    {
        /// <summary>The compounds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage? Compounds { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage Compounds { get; set; }
#endif
        /// <summary>The plurals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage? Plurals { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage Plurals { get; set; }
#endif
        /// <summary>The stopwords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage? Stopwords { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage Stopwords { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Languages"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Languages CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.Languages();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compounds", n => { Compounds = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>(global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage.CreateFromDiscriminatorValue); } },
                { "plurals", n => { Plurals = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>(global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage.CreateFromDiscriminatorValue); } },
                { "stopwords", n => { Stopwords = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>(global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>("compounds", Compounds);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>("plurals", Plurals);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.DictionaryLanguage>("stopwords", Stopwords);
        }
    }
}
#pragma warning restore CS0618
