// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_C_merged_openapi_merged_openapi_recommendationsRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery? MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery? MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery? MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery? MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery? MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_recommendationsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_recommendationsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_recommendationsRequest();
            if("C_merged_openapi_merged_openapi_boughtTogetherQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery();
            }
            else if("C_merged_openapi_merged_openapi_lookingSimilarQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery();
            }
            else if("C_merged_openapi_merged_openapi_relatedQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery();
            }
            else if("C_merged_openapi_merged_openapi_trendingFacetsQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery();
            }
            else if("C_merged_openapi_merged_openapi_trendingItemsQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery != null)
            {
                return MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery != null)
            {
                return MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery != null)
            {
                return MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery != null)
            {
                return MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery != null)
            {
                return MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_boughtTogetherQuery>(null, MergedOpenapiCMergedOpenapiMergedOpenapiBoughtTogetherQuery);
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_lookingSimilarQuery>(null, MergedOpenapiCMergedOpenapiMergedOpenapiLookingSimilarQuery);
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_relatedQuery>(null, MergedOpenapiCMergedOpenapiMergedOpenapiRelatedQuery);
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingFacetsQuery>(null, MergedOpenapiCMergedOpenapiMergedOpenapiTrendingFacetsQuery);
            }
            else if(MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_C_merged_openapi_merged_openapi_trendingItemsQuery>(null, MergedOpenapiCMergedOpenapiMergedOpenapiTrendingItemsQuery);
            }
        }
    }
}
#pragma warning restore CS0618
