// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Synonym type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_SynonymType
    {
        [EnumMember(Value = "synonym")]
        #pragma warning disable CS1591
        Synonym,
        #pragma warning restore CS1591
        [EnumMember(Value = "onewaysynonym")]
        #pragma warning disable CS1591
        Onewaysynonym,
        #pragma warning restore CS1591
        [EnumMember(Value = "altcorrection1")]
        #pragma warning disable CS1591
        Altcorrection1,
        #pragma warning restore CS1591
        [EnumMember(Value = "altcorrection2")]
        #pragma warning disable CS1591
        Altcorrection2,
        #pragma warning restore CS1591
        [EnumMember(Value = "placeholder")]
        #pragma warning disable CS1591
        Placeholder,
        #pragma warning restore CS1591
    }
}
