// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_ingestion_SourceUpdateInput : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery? MergedOpenapiIngestionSourceBigQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery MergedOpenapiIngestionSourceBigQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV? MergedOpenapiIngestionSourceCSV { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV MergedOpenapiIngestionSourceCSV { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport? MergedOpenapiIngestionSourceGA4BigQueryExport { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport MergedOpenapiIngestionSourceGA4BigQueryExport { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON? MergedOpenapiIngestionSourceJSON { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON MergedOpenapiIngestionSourceJSON { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools? MergedOpenapiIngestionSourceUpdateCommercetools { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools MergedOpenapiIngestionSourceUpdateCommercetools { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker? MergedOpenapiIngestionSourceUpdateDocker { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker MergedOpenapiIngestionSourceUpdateDocker { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify? MergedOpenapiIngestionSourceUpdateShopify { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify MergedOpenapiIngestionSourceUpdateShopify { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateInput();
            if("merged_openapi_ingestion_SourceBigQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceBigQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery();
            }
            else if("merged_openapi_ingestion_SourceCSV".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceCSV = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV();
            }
            else if("merged_openapi_ingestion_SourceGA4BigQueryExport".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceGA4BigQueryExport = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport();
            }
            else if("merged_openapi_ingestion_SourceJSON".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceJSON = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON();
            }
            else if("merged_openapi_ingestion_SourceUpdateCommercetools".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceUpdateCommercetools = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools();
            }
            else if("merged_openapi_ingestion_SourceUpdateDocker".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceUpdateDocker = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker();
            }
            else if("merged_openapi_ingestion_SourceUpdateShopify".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiIngestionSourceUpdateShopify = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MergedOpenapiIngestionSourceBigQuery != null)
            {
                return MergedOpenapiIngestionSourceBigQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceCSV != null)
            {
                return MergedOpenapiIngestionSourceCSV.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceGA4BigQueryExport != null)
            {
                return MergedOpenapiIngestionSourceGA4BigQueryExport.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceJSON != null)
            {
                return MergedOpenapiIngestionSourceJSON.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceUpdateCommercetools != null)
            {
                return MergedOpenapiIngestionSourceUpdateCommercetools.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceUpdateDocker != null)
            {
                return MergedOpenapiIngestionSourceUpdateDocker.GetFieldDeserializers();
            }
            else if(MergedOpenapiIngestionSourceUpdateShopify != null)
            {
                return MergedOpenapiIngestionSourceUpdateShopify.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MergedOpenapiIngestionSourceBigQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceBigQuery>(null, MergedOpenapiIngestionSourceBigQuery);
            }
            else if(MergedOpenapiIngestionSourceCSV != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceCSV>(null, MergedOpenapiIngestionSourceCSV);
            }
            else if(MergedOpenapiIngestionSourceGA4BigQueryExport != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceGA4BigQueryExport>(null, MergedOpenapiIngestionSourceGA4BigQueryExport);
            }
            else if(MergedOpenapiIngestionSourceJSON != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceJSON>(null, MergedOpenapiIngestionSourceJSON);
            }
            else if(MergedOpenapiIngestionSourceUpdateCommercetools != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateCommercetools>(null, MergedOpenapiIngestionSourceUpdateCommercetools);
            }
            else if(MergedOpenapiIngestionSourceUpdateDocker != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateDocker>(null, MergedOpenapiIngestionSourceUpdateDocker);
            }
            else if(MergedOpenapiIngestionSourceUpdateShopify != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_ingestion_SourceUpdateShopify>(null, MergedOpenapiIngestionSourceUpdateShopify);
            }
        }
    }
}
#pragma warning restore CS0618
