// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for the smallest difference between test variants you want to detect.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_abtesting_MinimumDetectableEffect : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Metric for which you want to detect the smallest relative difference.</summary>
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_EffectMetric? Metric { get; set; }
        /// <summary>Smallest difference in an observable metric between variants.For example, to detect a 10% difference between variants, set this value to 0.1.</summary>
        public double? Size { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_MinimumDetectableEffect"/> and sets the default values.
        /// </summary>
        public Merged_openapi_abtesting_MinimumDetectableEffect()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_MinimumDetectableEffect"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_MinimumDetectableEffect CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_MinimumDetectableEffect();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "metric", n => { Metric = n.GetEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_EffectMetric>(); } },
                { "size", n => { Size = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_abtesting_EffectMetric>("metric", Metric);
            writer.WriteDoubleValue("size", Size);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
