// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// [Redirect results to a URL](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/redirects), this this parameter is for internal use only.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The index property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_search_RedirectRuleIndexMetadata>? Index { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_search_RedirectRuleIndexMetadata> Index { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect"/> and sets the default values.
        /// </summary>
        public Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_browseResponse_redirect();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "index", n => { Index = n.GetCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_search_RedirectRuleIndexMetadata>(global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_search_RedirectRuleIndexMetadata.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_search_RedirectRuleIndexMetadata>("index", Index);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
