// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_merged_openapi_merged_openapi_recommendationsHit : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit? MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit? MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendationsHit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendationsHit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendationsHit();
            if("merged_openapi_merged_openapi_merged_openapi_recommendHit".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit();
            }
            else if("merged_openapi_merged_openapi_merged_openapi_trendingFacetHit".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit != null)
            {
                return MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit.GetFieldDeserializers();
            }
            else if(MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit != null)
            {
                return MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_recommendHit>(null, MergedOpenapiMergedOpenapiMergedOpenapiRecommendHit);
            }
            else if(MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_merged_openapi_merged_openapi_trendingFacetHit>(null, MergedOpenapiMergedOpenapiMergedOpenapiTrendingFacetHit);
            }
        }
    }
}
#pragma warning restore CS0618
