// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_SourceUpdateInput : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery? MergedOpenapiSourceBigQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery MergedOpenapiSourceBigQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV? MergedOpenapiSourceCSV { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV MergedOpenapiSourceCSV { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport? MergedOpenapiSourceGA4BigQueryExport { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport MergedOpenapiSourceGA4BigQueryExport { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON? MergedOpenapiSourceJSON { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON MergedOpenapiSourceJSON { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools? MergedOpenapiSourceUpdateCommercetools { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools MergedOpenapiSourceUpdateCommercetools { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker? MergedOpenapiSourceUpdateDocker { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker MergedOpenapiSourceUpdateDocker { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify? MergedOpenapiSourceUpdateShopify { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify MergedOpenapiSourceUpdateShopify { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateInput();
            if("merged_openapi_SourceBigQuery".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceBigQuery = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery();
            }
            else if("merged_openapi_SourceCSV".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceCSV = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV();
            }
            else if("merged_openapi_SourceGA4BigQueryExport".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceGA4BigQueryExport = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport();
            }
            else if("merged_openapi_SourceJSON".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceJSON = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON();
            }
            else if("merged_openapi_SourceUpdateCommercetools".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceUpdateCommercetools = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools();
            }
            else if("merged_openapi_SourceUpdateDocker".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceUpdateDocker = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker();
            }
            else if("merged_openapi_SourceUpdateShopify".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiSourceUpdateShopify = new global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MergedOpenapiSourceBigQuery != null)
            {
                return MergedOpenapiSourceBigQuery.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceCSV != null)
            {
                return MergedOpenapiSourceCSV.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceGA4BigQueryExport != null)
            {
                return MergedOpenapiSourceGA4BigQueryExport.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceJSON != null)
            {
                return MergedOpenapiSourceJSON.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceUpdateCommercetools != null)
            {
                return MergedOpenapiSourceUpdateCommercetools.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceUpdateDocker != null)
            {
                return MergedOpenapiSourceUpdateDocker.GetFieldDeserializers();
            }
            else if(MergedOpenapiSourceUpdateShopify != null)
            {
                return MergedOpenapiSourceUpdateShopify.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MergedOpenapiSourceBigQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceBigQuery>(null, MergedOpenapiSourceBigQuery);
            }
            else if(MergedOpenapiSourceCSV != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceCSV>(null, MergedOpenapiSourceCSV);
            }
            else if(MergedOpenapiSourceGA4BigQueryExport != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceGA4BigQueryExport>(null, MergedOpenapiSourceGA4BigQueryExport);
            }
            else if(MergedOpenapiSourceJSON != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceJSON>(null, MergedOpenapiSourceJSON);
            }
            else if(MergedOpenapiSourceUpdateCommercetools != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateCommercetools>(null, MergedOpenapiSourceUpdateCommercetools);
            }
            else if(MergedOpenapiSourceUpdateDocker != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateDocker>(null, MergedOpenapiSourceUpdateDocker);
            }
            else if(MergedOpenapiSourceUpdateShopify != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Merged_openapi_SourceUpdateShopify>(null, MergedOpenapiSourceUpdateShopify);
            }
        }
    }
}
#pragma warning restore CS0618
