// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>The impact that personalization has on the re-ranking of search results.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_fixed_personalizationReRanking
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "high")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
        [EnumMember(Value = "maximum")]
        #pragma warning disable CS1591
        Maximum,
        #pragma warning restore CS1591
    }
}
