// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Task status, `published` if the task is completed, `notPublished` otherwise.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_merged_openapi_merged_openapi_merged_openapi_recommend_taskStatus
    {
        [EnumMember(Value = "published")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "notPublished")]
        #pragma warning disable CS1591
        NotPublished,
        #pragma warning restore CS1591
    }
}
