// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>Sort order for A/B tests by start date.Use &apos;asc&apos; for ascending or &apos;desc&apos; for descending.Active A/B tests are always listed first.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_fixed_direction
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
    }
}
