// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Search_ignorePlurals : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper? SearchBooleanStringWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper SearchBooleanStringWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1? SearchIgnorePluralsBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1 SearchIgnorePluralsBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3? SearchIgnorePluralsBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3 SearchIgnorePluralsBranch3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals();
            if("search_booleanString".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SearchBooleanStringWrapper = new global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper();
            }
            else if("search_ignorePlurals_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SearchIgnorePluralsBranch1 = new global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1();
            }
            else if("search_ignorePlurals_3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SearchIgnorePluralsBranch3 = new global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SearchBooleanStringWrapper != null)
            {
                return SearchBooleanStringWrapper.GetFieldDeserializers();
            }
            else if(SearchIgnorePluralsBranch1 != null)
            {
                return SearchIgnorePluralsBranch1.GetFieldDeserializers();
            }
            else if(SearchIgnorePluralsBranch3 != null)
            {
                return SearchIgnorePluralsBranch3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SearchBooleanStringWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Search_booleanString_Wrapper>(null, SearchBooleanStringWrapper);
            }
            else if(SearchIgnorePluralsBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch1>(null, SearchIgnorePluralsBranch1);
            }
            else if(SearchIgnorePluralsBranch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.Search_ignorePlurals_Branch3>(null, SearchIgnorePluralsBranch3);
            }
        }
    }
}
#pragma warning restore CS0618
