// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1"/>, <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchInsideBoundingBox : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper? SearchInsideBoundingBoxArrayWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper SearchInsideBoundingBoxArrayWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1? SearchInsideBoundingBoxBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1 SearchInsideBoundingBoxBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxMember1? SearchInsideBoundingBoxMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxMember1 SearchInsideBoundingBoxMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBox();
            if("SearchInsideBoundingBoxArrayWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SearchInsideBoundingBoxArrayWrapper = new global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper();
            }
            else if("SearchInsideBoundingBoxBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SearchInsideBoundingBoxBranch1 = new global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SearchInsideBoundingBoxArrayWrapper != null)
            {
                return SearchInsideBoundingBoxArrayWrapper.GetFieldDeserializers();
            }
            else if(SearchInsideBoundingBoxBranch1 != null)
            {
                return SearchInsideBoundingBoxBranch1.GetFieldDeserializers();
            }
            else if(SearchInsideBoundingBoxMember1 != null)
            {
                return SearchInsideBoundingBoxMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SearchInsideBoundingBoxArrayWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxArrayWrapper>(null, SearchInsideBoundingBoxArrayWrapper);
            }
            else if(SearchInsideBoundingBoxBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxBranch1>(null, SearchInsideBoundingBoxBranch1);
            }
            else if(SearchInsideBoundingBoxMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.SearchInsideBoundingBoxMember1>(null, SearchInsideBoundingBoxMember1);
            }
        }
    }
}
#pragma warning restore CS0618
