// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Algolia.OpenApiClient.Models
{
    /// <summary>
    /// API request body for creating a task using the V1 shape. Use methods and types that don&apos;t contain the V1 suffix.
    /// </summary>
    [Obsolete("")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskCreateV1 : IParsable
    {
        /// <summary>Action to perform on the Algolia index.</summary>
        public global::Soenneker.Algolia.OpenApiClient.Models.ActionType? Action { get; set; }
        /// <summary>Date and time when the last cursor was created, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>Universally unique identifier (UUID) of a destination resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationID { get; set; }
#nullable restore
#else
        public string DestinationID { get; set; }
#endif
        /// <summary>Whether the task is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Maximum accepted percentage of failures for a task run to finish successfully.</summary>
        public int? FailureThreshold { get; set; }
        /// <summary>Configuration of the task, depending on its type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.TaskInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.TaskInput Input { get; set; }
#endif
        /// <summary>Universally uniqud identifier (UUID) of a source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceID { get; set; }
#nullable restore
#else
        public string SourceID { get; set; }
#endif
        /// <summary>The trigger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateTrigger? Trigger { get; set; }
#nullable restore
#else
        public global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateTrigger Trigger { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.ActionType>(); } },
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "destinationID", n => { DestinationID = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "failureThreshold", n => { FailureThreshold = n.GetIntValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.TaskInput>(global::Soenneker.Algolia.OpenApiClient.Models.TaskInput.CreateFromDiscriminatorValue); } },
                { "sourceID", n => { SourceID = n.GetStringValue(); } },
                { "trigger", n => { Trigger = n.GetObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateTrigger>(global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateTrigger.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Algolia.OpenApiClient.Models.ActionType>("action", Action);
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteStringValue("destinationID", DestinationID);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("failureThreshold", FailureThreshold);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.TaskInput>("input", Input);
            writer.WriteStringValue("sourceID", SourceID);
            writer.WriteObjectValue<global::Soenneker.Algolia.OpenApiClient.Models.TaskCreateTrigger>("trigger", Trigger);
        }
    }
}
#pragma warning restore CS0618
