// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Batch;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Objects;
using Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Queries;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk
{
    /// <summary>
    /// Builds and executes requests for operations under \merged-openapi\fixed\merged-openapi\search\1\indexes\*
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batch property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Batch.BatchRequestBuilder Batch
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The objects property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Objects.ObjectsRequestBuilder Objects
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Objects.ObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queries property</summary>
        public global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Queries.QueriesRequestBuilder Queries
        {
            get => new global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.Queries.QueriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/merged-openapi/search/1/indexes/*", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.MergedOpenapi.Fixed.MergedOpenapi.Search.One.Indexes.Asterisk.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/merged-openapi/fixed/merged-openapi/search/1/indexes/*", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
