// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item.Probes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\monitoring\1\reachability\{clusters}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithClustersItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The probes property</summary>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item.Probes.ProbesRequestBuilder Probes
        {
            get => new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item.Probes.ProbesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item.WithClustersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithClustersItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/monitoring/1/reachability/{clusters}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Monitoring.One.Reachability.Item.WithClustersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithClustersItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/monitoring/1/reachability/{clusters}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
