// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Algolia.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\merged-openapi\fixed\search\generateSecuredApiKey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GenerateSecuredApiKeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenerateSecuredApiKeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/search/generateSecuredApiKey?parentApiKey={parentApiKey}&restrictions={restrictions}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenerateSecuredApiKeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/merged-openapi/fixed/search/generateSecuredApiKey?parentApiKey={parentApiKey}&restrictions={restrictions}", rawUrl)
        {
        }
        /// <summary>
        /// Generates a secured API key without any requests to Algolia&apos;s servers.Secured API keys are API keys that you generate on your server without any API request to Algolia.Use secured API keys when you can&apos;t update client-side code, such as in mobile apps,or when you need to restrict access to part of an index for each user.When users start searching, your app requests a short-lived secured API key from your server instead of using the Search API key.Your server uses this method to generate the secured API key with restrictions such as filters, index access restrictions,or expiration times, and returns it to your app. The API key gets longer as you add restrictions.You can&apos;t create secured API keys from other secured API keys or from your Admin API key.The generated API key can have the same restrictions as the parent API key, or be more restrictive.
        /// </summary>
        /// <returns>A <see cref="string"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_search_ErrorBase">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<string?> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder.GenerateSecuredApiKeyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<string> GetAsync(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder.GenerateSecuredApiKeyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Algolia.OpenApiClient.Models.C_merged_openapi_search_ErrorBase.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<string>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Generates a secured API key without any requests to Algolia&apos;s servers.Secured API keys are API keys that you generate on your server without any API request to Algolia.Use secured API keys when you can&apos;t update client-side code, such as in mobile apps,or when you need to restrict access to part of an index for each user.When users start searching, your app requests a short-lived secured API key from your server instead of using the Search API key.Your server uses this method to generate the secured API key with restrictions such as filters, index access restrictions,or expiration times, and returns it to your app. The API key gets longer as you add restrictions.You can&apos;t create secured API keys from other secured API keys or from your Admin API key.The generated API key can have the same restrictions as the parent API key, or be more restrictive.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder.GenerateSecuredApiKeyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder.GenerateSecuredApiKeyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Algolia.OpenApiClient.Fixed.MergedOpenapi.Fixed.Search.GenerateSecuredApiKey.GenerateSecuredApiKeyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Generates a secured API key without any requests to Algolia&apos;s servers.Secured API keys are API keys that you generate on your server without any API request to Algolia.Use secured API keys when you can&apos;t update client-side code, such as in mobile apps,or when you need to restrict access to part of an index for each user.When users start searching, your app requests a short-lived secured API key from your server instead of using the Search API key.Your server uses this method to generate the secured API key with restrictions such as filters, index access restrictions,or expiration times, and returns it to your app. The API key gets longer as you add restrictions.You can&apos;t create secured API keys from other secured API keys or from your Admin API key.The generated API key can have the same restrictions as the parent API key, or be more restrictive.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GenerateSecuredApiKeyRequestBuilderGetQueryParameters 
        {
            /// <summary>API key from which the secured API key will inherit its restrictions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parentApiKey")]
            public string? ParentApiKey { get; set; }
#nullable restore
#else
            [QueryParameter("parentApiKey")]
            public string ParentApiKey { get; set; }
#endif
            /// <summary>Restrictions to add to the API key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("restrictions")]
            public string? Restrictions { get; set; }
#nullable restore
#else
            [QueryParameter("restrictions")]
            public string Restrictions { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
